export const aadharOcrSampleImages = [
  {
    id: 1,
    thumbnail_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-1.jpg",
    original_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-1.jpg",
    selected: false,
  },
  {
    id: 2,
    thumbnail_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-2.jpg",
    original_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-2.jpg",
    selected: false,
  },
  {
    id: 3,
    thumbnail_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-3.jpg",
    original_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-3.jpg",
    selected: false,
  },
  {
    id: 4,
    thumbnail_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-4.jpg",
    original_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-4.jpg",
    selected: false,
  },
  {
    id: 5,
    thumbnail_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-5.jpg",
    original_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-5.jpg",
    selected: false,
  },
  {
    id: 6,
    thumbnail_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-6.jpg",
    original_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-6.jpg",
    selected: false,
  },
  {
    id: 7,
    thumbnail_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-7.jpg",
    original_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-7.jpg",
    selected: false,
  },
  {
    id: 8,
    thumbnail_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-8.jpg",
    original_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-8.jpg",
    selected: false,
  },
  {
    id: 9,
    thumbnail_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-9.jpg",
    original_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-9.jpg",
    selected: false,
  },
  {
    id: 10,
    thumbnail_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-10.jpg",
    original_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-10.jpg",
    selected: false,
  },
  {
    id: 11,
    thumbnail_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-11.jpg",
    original_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-11.jpg",
    selected: false,
  },
  {
    id: 12,
    thumbnail_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-12.jpg",
    original_path: "../pre-trained-sample-images/aadhar-ocr/Adhaar-Card-12.jpg",
    selected: false,
  },
];
export const panOcrSampleImages = [
  {
    id: 1,
    thumbnail_path: "../pre-trained-sample-images/pan-ocr/pan1.jpg",
    original_path: "../pre-trained-sample-images/pan-ocr/pan1.jpg",
    selected: false,
  },
  {
    id: 2,
    thumbnail_path: "../pre-trained-sample-images/pan-ocr/pan2.jpg",
    original_path: "../pre-trained-sample-images/pan-ocr/pan2.jpg",
    selected: false,
  },
  {
    id: 3,
    thumbnail_path: "../pre-trained-sample-images/pan-ocr/pan3.jpg",
    original_path: "../pre-trained-sample-images/pan-ocr/pan3.jpg",
    selected: false,
  },
  {
    id: 4,
    thumbnail_path: "../pre-trained-sample-images/pan-ocr/pan4.jpg",
    original_path: "../pre-trained-sample-images/pan-ocr/pan4.jpg",
    selected: false,
  },
  {
    id: 5,
    thumbnail_path: "../pre-trained-sample-images/pan-ocr/pan5.jpg",
    original_path: "../pre-trained-sample-images/pan-ocr/pan5.jpg",
    selected: false,
  },
  {
    id: 6,
    thumbnail_path: "../pre-trained-sample-images/pan-ocr/pan6.jpg",
    original_path: "../pre-trained-sample-images/pan-ocr/pan6.jpg",
    selected: false,
  },
  {
    id: 7,
    thumbnail_path: "../pre-trained-sample-images/pan-ocr/pan7.jpg",
    original_path: "../pre-trained-sample-images/pan-ocr/pan7.jpg",
    selected: false,
  },
  {
    id: 8,
    thumbnail_path: "../pre-trained-sample-images/pan-ocr/pan8.jpg",
    original_path: "../pre-trained-sample-images/pan-ocr/pan8.jpg",
    selected: false,
  },
  {
    id: 9,
    thumbnail_path: "../pre-trained-sample-images/pan-ocr/pan9.jpg",
    original_path: "../pre-trained-sample-images/pan-ocr/pan9.jpg",
    selected: false,
  },
  {
    id: 10,
    thumbnail_path: "../pre-trained-sample-images/pan-ocr/pan10.jpg",
    original_path: "../pre-trained-sample-images/pan-ocr/pan10.jpg",
    selected: false,
  },
  {
    id: 11,
    thumbnail_path: "../pre-trained-sample-images/pan-ocr/pan11.jpg",
    original_path: "../pre-trained-sample-images/pan-ocr/pan11.jpg",
    selected: false,
  },
  {
    id: 12,
    thumbnail_path: "../pre-trained-sample-images/pan-ocr/pan12.jpg",
    original_path: "../pre-trained-sample-images/pan-ocr/pan12.jpg",
    selected: false,
  },
];
export const voterOcrSampleImages = [
  {
    id: 1,
    thumbnail_path: "../pre-trained-sample-images/voter-ocr/VoterCard1.jpg",
    original_path: "../pre-trained-sample-images/voter-ocr/VoterCard1.jpg",
    selected: false,
  },
  {
    id: 2,
    thumbnail_path: "../pre-trained-sample-images/voter-ocr/VoterCard2.jpg",
    original_path: "../pre-trained-sample-images/voter-ocr/VoterCard2.jpg",
    selected: false,
  },
  {
    id: 3,
    thumbnail_path: "../pre-trained-sample-images/voter-ocr/VoterCard3.jpg",
    original_path: "../pre-trained-sample-images/voter-ocr/VoterCard3.jpg",
    selected: false,
  },
  {
    id: 4,
    thumbnail_path: "../pre-trained-sample-images/voter-ocr/VoterCard4.jpg",
    original_path: "../pre-trained-sample-images/voter-ocr/VoterCard4.jpg",
    selected: false,
  },
  {
    id: 5,
    thumbnail_path: "../pre-trained-sample-images/voter-ocr/VoterCard5.jpg",
    original_path: "../pre-trained-sample-images/voter-ocr/VoterCard5.jpg",
    selected: false,
  },
  {
    id: 6,
    thumbnail_path: "../pre-trained-sample-images/voter-ocr/VoterCard6.jpg",
    original_path: "../pre-trained-sample-images/voter-ocr/VoterCard6.jpg",
    selected: false,
  },
  {
    id: 7,
    thumbnail_path: "../pre-trained-sample-images/voter-ocr/VoterCard7.jpg",
    original_path: "../pre-trained-sample-images/voter-ocr/VoterCard7.jpg",
    selected: false,
  },
  {
    id: 8,
    thumbnail_path: "../pre-trained-sample-images/voter-ocr/VoterCard8.jpg",
    original_path: "../pre-trained-sample-images/voter-ocr/VoterCard8.jpg",
    selected: false,
  },
  {
    id: 9,
    thumbnail_path: "../pre-trained-sample-images/voter-ocr/VoterCard9.jpg",
    original_path: "../pre-trained-sample-images/voter-ocr/VoterCard9.jpg",
    selected: false,
  },
  {
    id: 10,
    thumbnail_path: "../pre-trained-sample-images/voter-ocr/VoterCard10.jpg",
    original_path: "../pre-trained-sample-images/voter-ocr/VoterCard10.jpg",
    selected: false,
  },
  {
    id: 11,
    thumbnail_path: "../pre-trained-sample-images/voter-ocr/VoterCard11.jpg",
    original_path: "../pre-trained-sample-images/voter-ocr/VoterCard11.jpg",
    selected: false,
  },
  {
    id: 12,
    thumbnail_path: "../pre-trained-sample-images/voter-ocr/VoterCard12.jpg",
    original_path: "../pre-trained-sample-images/voter-ocr/VoterCard12.jpg",
    selected: false,
  },
];
